version: '3.8'

services:
  redis:
    image: redis
    container_name: my-redis-container
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
      - ./pokemon-data.txt:/tmp/pokemon-data.txt
    restart: always
