version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_USER: sandbox
      POSTGRES_PASSWORD: sandboxProject
    ports:
      - "5433:5432"
    container_name: postgres_container
