version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: demodb
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: example
    ports:
      - "5433:5432"
    container_name: postgres_container
